name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up bazel
        uses: bazel-contrib/setup-bazel@0.9.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          bazelrc: |
            common --enable_bzlmod
            common --java_language_version=21
            common --java_runtime_version=21
            coverage --combined_report=lcov

      - name: Run tests with coverage
        run: bazel coverage //...

      - name: Copy Test Results
        if: always()
        run: |
          cp -Lpr bazel-testlogs .generated

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.18.0
        if: always()
        with:
          files: .generated/bazel-testlogs/**/test.xml

      - name: Upload coverage data
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: bazel-out/_coverage/_coverage_report.dat
          token: ${{ secrets.CODECOV_TOKEN }}
